version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-account-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_DATABASE: bpEbank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: