version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-account-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_DATABASE: bpEbank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - accounts-analytics

  axonserver:
    image: 'axoniq/axonserver:latest'
    container_name: axonserver
    environment:
      - 'AXONIQ_AXONSERVER_STANDALONE=true'
    ports:
      - '8024:8024'
      - '8124:8124'
    networks:
      - accounts-analytics

volumes:
  mysql_data:

networks:
  accounts-analytics:
    driver: bridge
